/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestRouteImport } from './routes/best'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as StorySlugRouteImport } from './routes/story.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestRoute = BestRouteImport.update({
  id: '/best',
  path: '/best',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/api/generate': typeof ApiGenerateRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/api/generate': typeof ApiGenerateRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best': typeof BestRoute
  '/api/generate': typeof ApiGenerateRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/best' | '/api/generate' | '/story/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/best' | '/api/generate' | '/story/$slug'
  id: '__root__' | '/' | '/best' | '/api/generate' | '/story/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestRoute: typeof BestRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  StorySlugRoute: typeof StorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best': {
      id: '/best'
      path: '/best'
      fullPath: '/best'
      preLoaderRoute: typeof BestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestRoute: BestRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  StorySlugRoute: StorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
